#
# MacOSX ("Mac OS X" => MacOSX) M1 (64 bits)
#

aarch64.MacOSX.linker=g++

aarch64.MacOSX.gpp.cpp.compiler=g++
aarch64.MacOSX.gpp.cpp.defines=Darwin GNU_GCC 
aarch64.MacOSX.gpp.cpp.options=-Wall -Wno-long-long -Wpointer-arith -Wconversion
aarch64.MacOSX.gpp.cpp.includes=**/*.cc **/*.cpp **/*.cxx
aarch64.MacOSX.gpp.cpp.excludes=

aarch64.MacOSX.gpp.c.compiler=gcc
aarch64.MacOSX.gpp.c.defines=Darwin GNU_GCC 
aarch64.MacOSX.gpp.c.options=-Wall -Wno-long-long -Wpointer-arith -Wconversion
aarch64.MacOSX.gpp.c.includes=**/*.c
aarch64.MacOSX.gpp.c.excludes=

aarch64.MacOSX.gpp.fortran.compiler=gfortran
aarch64.MacOSX.gpp.fortran.defines=Darwin GNU_GCC 
aarch64.MacOSX.gpp.fortran.options=-Wall -fno-automatic -fno-second-underscore
aarch64.MacOSX.gpp.fortran.includes=**/*.f **/*.for
aarch64.MacOSX.gpp.fortran.excludes=

aarch64.MacOSX.gpp.java.include=include;include/darwin
aarch64.MacOSX.gpp.java.runtimeDirectory=IGNORED

aarch64.MacOSX.gpp.lib.prefix=lib
aarch64.MacOSX.gpp.shared.prefix=lib
aarch64.MacOSX.gpp.static.extension=a
aarch64.MacOSX.gpp.shared.extension=dylib
aarch64.MacOSX.gpp.plugin.extension=bundle
aarch64.MacOSX.gpp.jni.extension=jnilib
aarch64.MacOSX.gpp.executable.extension=

